info:
  contact: {}
paths:
  /ticker:
    get:
      consumes:
      - application/json
      description: test
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: ticker test
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
