info:
  contact: {}
paths:
  /ticker:
    get:
      consumes:
      - application/json
      description: insert tickers
      produces:
      - application/json
      responses: {}
      summary: ticker
  /ticker/daycandle:
    get:
      consumes:
      - application/json
      description: insert daycandles
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: day candles
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
