info:
  contact: {}
paths:
  /ticker:
    get:
      consumes:
      - application/json
      description: insert tickers
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: ticker
  /ticker/daycandle:
    get:
      consumes:
      - application/json
      description: insert daycandles
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: day candles
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
