version: "3.8"
services:
  gocron:
    build:
      context: "./go"
      dockerfile: Dockerfile
      args:
        - GITACCOUNT=${GIT_ACCOUNT}
        - GITTOKEN=${GIT_TOKEN}
    container_name: gocron
    restart: always
    ports:
      - 8000:8000
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
    env_file:
      - ./.env
    volumes:
      - ./go:/app
      - /tmp/mysqld:/run/mysqld
  springapi:
    build:
      context: "./spring"
      dockerfile: Dockerfile.api.dev
    container_name: springapi
    restart: always
    ports:
      - 8090:8090
    env_file:
      - ./.env
    volumes:
      - "./spring/api:/app/api"
      - "/api/api_gradle" # Gradle cache
      - "./spring/api/.gradle:/app/api/.gradle"
  ws:
    build:
      context: "./spring"
      dockerfile: Dockerfile.ws.dev
    container_name: ws
    restart: always
    ports:
      - 8100:8100
    env_file:
      - ./.env
    volumes:
      - "./spring/ws:/wsapp/ws"
      - "/ws/ws_gradle" # Gradle cache
      - "./spring/ws/.gradle:/wsapp/ws/.gradle"
