version: "3"
services:
  gocron:
    build:
      context: "./go"
      dockerfile: Dockerfile
      args:
        - GITACCOUNT=${GIT_ACCOUNT}
        - GITTOKEN=${GIT_TOKEN}
    container_name: gocron
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./go:/app
      - /tmp/mysqld:/run/mysqld
  springapi:
    build:
      context: "./spring"
      dockerfile: Dockerfile.dev
    container_name: springapi
    restart: always
    ports:
      - 8090:8090
    env_file:
      - ./.env
    volumes:
      - "./spring:/app"
      - "./spring/build:/app/build"
