FROM gradle:8.10-jdk17 AS build-env

WORKDIR /springapi

COPY settings.gradle build.gradle run-dev.sh /springapi/

COPY api /springapi/api
COPY core /springapi/core

RUN chmod +x run-dev.sh
RUN gradle dependencies --no-daemon || true
RUN gradle build -x test --no-daemon

EXPOSE 8090

ENTRYPOINT ["sh", "run-dev.sh"]
