# Dockerfile.dev
FROM gradle:8.10-jdk17

WORKDIR /app

COPY api /app/api
COPY core /app/core
COPY build.gradle /app/
COPY settings.gradle /app/

RUN gradle dependencies --no-daemon || true

EXPOSE 8090
ENTRYPOINT ["sh", "-c", "(gradle build -x test --continuous) & gradle api:bootRun -Dspring.profiles.active=dev"]
