# Dockerfile.dev
FROM gradle:8.10-jdk17

WORKDIR /app

COPY api /app/api
COPY core /app/core
COPY build.gradle /app/
COPY settings.gradle /app/

RUN gradle dependencies --no-daemon || true
RUN gradle build -x test --no-daemon

EXPOSE 8090

ENTRYPOINT ["sh", "-c", "(./gradlew :core:build -x test --continuous) & (./gradlew build -x test --continuous) & ./gradlew api:bootRun -Dspring.profiles.active=dev"]
