FROM gradle:8.12-jdk21 AS builder

WORKDIR /app

COPY api /app/api
COPY core /app/core
COPY build.gradle /app/
COPY settings.gradle /app/

RUN gradle dependencies

RUN gradle api:build core:build

FROM openjdk:21-slim

WORKDIR /app

COPY --from=builder /app/api/build/libs/api-*.jar /app/api.jar

ENV SPRING_PROFILES_ACTIVE=prod

EXPOSE 8090

CMD ["java", "-jar", "/app/api.jar"]