# Dockerfile.dev
FROM gradle:8.12-jdk21

WORKDIR /app

COPY api /app/api
COPY core /app/core
COPY build.gradle /app/
COPY settings.gradle /app/

RUN gradle dependencies --no-daemon || true

EXPOSE 8090
ENTRYPOINT ["sh", "-c", "(gradle api:build -x test --continuous) & (gradle core:build -x test --continuous)  & gradle api:bootRun -Dspring.profiles.active=dev"]
